from numpy import random
from algorithms.environment_oop import Environment

from typing import List


def quick_sort(env: Environment) -> List[int]:
    stack_index_in_arr_low: int = env.bind_reg(0, 1)
    value_at_stack_index_in_arr_low: int = env.bind_arr(0, 1, 2) #
    stack_index_in_arr_high: int = env.bind_reg(1, 1) #
    value_at_stack_index_in_arr_high: int = env.bind_arr(1, 1, 2) #
    index_in_arr_high_predecessor: int = env.bind_reg(0, 0)
    value_at_index_in_arr_high_predecessor: int = env.bind_arr(0, 0, 2) #
    index_in_arr_cur: int = env.bind_reg(1, 0)
    value_at_index_in_arr_cur: int = env.bind_arr(1, 0, 2)
    index_in_arr_out_of_order: int = env.bind_reg(2, 0)#
    value_at_index_in_arr_out_of_order: int = env.bind_arr(2, 0, 2) #
    index_in_arr_out_of_order_suc: int = env.bind_reg(3, 0)
    value_at_index_in_arr_out_of_order_suc: int = env.bind_arr(3, 0, 2)
    index_in_arr_out_of_order_suc_suc: int = env.bind_reg(4, 0)
    value_at_index_in_arr_out_of_order_suc_suc: int = env.bind_arr(4, 0, 2)
    #  Variables
    var_pivot: int = env.bind_reg(5, 0)
    var_temp: int = env.bind_reg(6, 0)
    var_in_arr_low: int = env.bind_reg(7, 0)
    var_in_arr_high: int = env.bind_reg(8, 0)
    # Start
    env.stack.push_address_type(1)
    env.stack.push_constant(0)
    env.stack.push_constant(0)
    env.stack.store()
    env.stack.push_address_type(1)
    env.stack.push_constant(1)
    env.stack.push_in_arr_length()
    env.stack.push_constant(1)
    env.stack.sub()
    env.stack.store()
    env.stack_register_file.push_register_file_stack()
    while 2 <= len(env.stack_register_file.register_file_stack):
        env.stack_register_file.pop_register_file_stack()
        env.stack.push_address_type(0)
        env.stack.push_constant(0)
        env.stack.push_address_type(1)
        env.stack.push_constant(1)
        env.stack.push()
        env.stack.push_constant(1)
        env.stack.sub()
        env.stack.store()
        if env.value_reg(stack_index_in_arr_low) <= env.value_reg(index_in_arr_high_predecessor):
            env.stack.push_address_type(0)
            env.stack.push_constant(5)
            env.stack.push_address_type(2)
            env.stack.push_address_type(1)
            env.stack.push_constant(1)
            env.stack.push()
            env.stack.push()
            env.stack.store()
            env.stack.push_address_type(0)
            env.stack.push_constant(2)
            env.stack.push_address_type(1)
            env.stack.push_constant(0)
            env.stack.push()
            env.stack.push_constant(1)
            env.stack.sub()
            env.stack.store()
            env.stack.push_address_type(0)
            env.stack.push_constant(1)
            env.stack.push_address_type(1)
            env.stack.push_constant(0)
            env.stack.push()
            env.stack.store()
            env.stack.push_address_type(0)
            env.stack.push_constant(0)
            env.stack.push_address_type(1)
            env.stack.push_constant(1)
            env.stack.push()
            env.stack.push_constant(1)
            env.stack.sub()
            env.stack.store()
            while env.value_reg(index_in_arr_cur) <= env.value_reg(index_in_arr_high_predecessor):
                env.set_program_counter(51)
                if env.value_arr(value_at_index_in_arr_cur) <= env.value_reg(var_pivot):
                    env.stack.push_address_type(0)
                    env.stack.push_constant(2)
                    env.stack.push_address_type(0)
                    env.stack.push_constant(2)
                    env.stack.push()
                    env.stack.push_constant(1)
                    env.stack.add()
                    env.stack.store()
                    env.stack.push_address_type(0)
                    env.stack.push_constant(6)
                    env.stack.push_address_type(2)
                    env.stack.push_address_type(0)
                    env.stack.push_constant(1)
                    env.stack.push()
                    env.stack.push()
                    env.stack.store()
                    env.stack.push_address_type(2)
                    env.stack.push_address_type(0)
                    env.stack.push_constant(1)
                    env.stack.push()
                    env.stack.push_address_type(2)
                    env.stack.push_address_type(0)
                    env.stack.push_constant(2)
                    env.stack.push()
                    env.stack.push()
                    env.stack.store()
                    env.stack.push_address_type(2)
                    env.stack.push_address_type(0)
                    env.stack.push_constant(2)
                    env.stack.push()
                    env.stack.push_address_type(0)
                    env.stack.push_constant(6)
                    env.stack.push()
                    env.stack.store()
                else:
                    env.set_program_counter(85)
                env.stack.push_address_type(0)
                env.stack.push_constant(1)
                env.stack.push_address_type(0)
                env.stack.push_constant(1)
                env.stack.push()
                env.stack.push_constant(1)
                env.stack.add()
                env.stack.store()
                env.stack.push_address_type(0)
                env.stack.push_constant(0)
                env.stack.push_address_type(1)
                env.stack.push_constant(1)
                env.stack.push()
                env.stack.push_constant(1)
                env.stack.sub()
                env.stack.store()
                env.set_program_counter(50)
            else:
                env.set_program_counter(102)
            env.stack.push_address_type(0)
            env.stack.push_constant(3)
            env.stack.push_address_type(0)
            env.stack.push_constant(2)
            env.stack.push()
            env.stack.push_constant(1)
            env.stack.add()
            env.stack.store()
            env.stack.push_address_type(0)
            env.stack.push_constant(6)
            env.stack.push_address_type(2)
            env.stack.push_address_type(0)
            env.stack.push_constant(3)
            env.stack.push()
            env.stack.push()
            env.stack.store()
            env.stack.push_address_type(2)
            env.stack.push_address_type(0)
            env.stack.push_constant(3)
            env.stack.push()
            env.stack.push_address_type(2)
            env.stack.push_address_type(1)
            env.stack.push_constant(1)
            env.stack.push()
            env.stack.push()
            env.stack.store()
            env.stack.push_address_type(2)
            env.stack.push_address_type(1)
            env.stack.push_constant(1)
            env.stack.push()
            env.stack.push_address_type(0)
            env.stack.push_constant(6)
            env.stack.push()
            env.stack.store()
            env.stack.push_address_type(0)
            env.stack.push_constant(7)
            env.stack.push_address_type(1)
            env.stack.push_constant(0)
            env.stack.push()
            env.stack.store()
            env.stack.push_address_type(0)
            env.stack.push_constant(8)
            env.stack.push_address_type(1)
            env.stack.push_constant(1)
            env.stack.push()
            env.stack.store()
            env.stack.push_address_type(1)
            env.stack.push_constant(1)
            env.stack.push_address_type(0)
            env.stack.push_constant(2)
            env.stack.push()
            env.stack.store()
            env.stack.push_address_type(1)
            env.stack.push_constant(0)
            env.stack.push_address_type(0)
            env.stack.push_constant(7)
            env.stack.push()
            env.stack.store()
            env.stack_register_file.push_register_file_stack()
            env.stack.push_address_type(1)
            env.stack.push_constant(1)
            env.stack.push_address_type(0)
            env.stack.push_constant(8)
            env.stack.push()
            env.stack.store()
            env.stack.push_address_type(0)
            env.stack.push_constant(4)
            env.stack.push_address_type(0)
            env.stack.push_constant(2)
            env.stack.push()
            env.stack.push_constant(2)
            env.stack.add()
            env.stack.store()
            env.stack.push_address_type(1)
            env.stack.push_constant(0)
            env.stack.push_address_type(0)
            env.stack.push_constant(4)
            env.stack.push()
            env.stack.store()
            env.stack_register_file.push_register_file_stack()
            env.set_program_counter(11)
        else:
            env.set_program_counter(11)
    else:
        env.set_program_counter(183)
    return env.in_arr

def gen_quick_sort_environment(problem: List[int]) -> Environment:
    return Environment(problem, [], [], 9, 2, include_stack_length=True)

